app:
  name: "My FastAPI App"
  version: "1.0.0"
  debug: true

database:
  url: "postgresql://user:password@localhost:5432/mydb"
  pool_size: 5

server:
  host: "0.0.0.0"
  port: 8000

azure:
  storage_account_name: "yourstorageaccount"
  storage_account_key: "yourstoragekey"
  storage_container: "yourcontainer"
  cosmos_db_endpoint: "https://your-cosmos-db.documents.azure.com:443/"
  cosmos_db_key: "yourcosmosdbkey"

openai:
  api_key: "your-openai-api-key"
  organization: "your-org-id"
  api_base: "https://api.openai.com/v1"  # Or your Azure OpenAI endpoint
  api_version: "2023-05-15"  # For Azure OpenAI
  deployment_name: "your-deployment-name"  # For Azure OpenAI