from PIL import Image
import easyocr
import numpy as np

reader = easyocr.Reader(['en'])


def get_image_text(image_path, language=["en"]):
    """
    Extracts text from an image using Surya OCR.

    Args:
        image_path (str): Path to the image file.
        language (list, optional): List of languages to use for text recognition. Default is ["en"].

    Returns:
        list: A list of extracted text lines from the image.
    """
    
    # Open the image file
    image = Image.open(image_path)

    # Load the detection model and processor
    det_processor, det_model = segformer.load_processor(), segformer.load_model()

    # Load the recognition model and processor
    rec_model, rec_processor = load_model(), load_processor()

    # Run the OCR process on the image
    predictions = run_ocr([image], [language], det_model, det_processor, rec_model, rec_processor)[0]

    # Extract text from the OCR predictions
    text = [line.text for line in list(predictions)[0][1]]
    
    return text



def ocr_easyocr(images:list)-> dict:
    '''EasyOCR extractor'''
    results = []
    
    for img in images:
        img_np = np.array(img)  # Convert PIL image to NumPy array
        text = " ".join([detection[1] for detection in reader.readtext(img_np)])
        results.append(text)
        
    return results


def get_extracted_text():
    return  [
    "CDS. Examination-(I), 2025 T 76 a461 %e Wiletut YEaT UaA &1 7 &37 &Q 7a 767 *la} &. &. #: CEBN-S-GKL Taror gaanT 313067 ;4 FG4T Wtaor yfraant 1134193 MTHG MN A 7T ; #&2 100 3an 1. qe YRTV 84 # 37 &1e, 314 5 gfaat &1 WenTad 3a94 & 4 f 713 f7 04, nz7 &1 &2T g817 9e 3r2Ta7 9p7i?, 31f< 7 & & W &, M  Hdt Whaur yfraqt # aqat 4 | 2. 0441 817 Td f& OMR J-4ET #, afam TVIF W, TG TTR 3k Tamur yqT 3j67 A,B, C # D 3, &M# va f7 fvit 5G & fafa & IA 3 &rar #4 8 fHarft 3rriaar *1 & fht # YaT 81 5o/farifa 4 Trena # 37-476 FRT &r fa41 5iqMt 3. 3 4feut 9faT 4 %4 # fey TQ 4o3vh # 3114351 31441 31h4io frTCHT 8 Tflam gAGT 4 3987 frd 4 34 4flau yo5T 4 120 TRT (T7) fq 7r & 57o TRT?I faret 31 avff <d 4 341 & 974a 4TYT #ATyar (3) feq nr & 34 4 0 TrJm #1 97 4, f 3114 3r-4AF 4 3fhd T *aa & 4 3114a1 QHT & fa VG5 # 31f045 Tryr %0} &, & 34 TrYT #1 3fhd *7 v 31191 Tal7h < 97a5 YHTR & fQ #aa UG & Tjm JTT 8 | 52 3114o61 3194 mfl THr 3T1 # fr TQ 37-477F 4 & 3f7 #9 & 37R-4TF 4 frq TQ fcv & 6. 7f 5rvrI & 314 HAN < | 7. 34 Tadt fa 31Y 4flzg 9fFaFT & fafF WA & TrIr 37-47V 4 3f0 TA %6 %7, 310471 xavi 9ATU-4A & H4 %fa 31ar1 & 31HR 30 faqu 37-45G 4& 8 | 8. 3714 3747 7ff 41 37-47G # IA $ &1 74 Tlu & HATIA W #7c7 3rK-4AV  31efF %1 %i9 4 311431 3144 4rq 4fletut 9 JA & 8 | 9 3a 414 & 9735 4flau gfaoF & 3a 4 ra5 8 | 10. Taa 3TI & 8 97.T7 # 3rfqaR ERI far TV TaT JTRT & & frt 5UMT 97 4 & fy AR do/4a 3n 8 / 3HfaaR ER 174a 1v7 & fr fr TQ V5 TTd JT & fiq 57 & Aa TQ 34o51 #1 Q-flals & $ 6y 4 #TT s1QT (ii) a 418 3HdR Vo5 # 3f8a5 377 &a1 &, 7 3 Tai JT HIT JQT, 4afq faq TQ Jir # 4 03 JT #8 ela1 &, f9r # 3& T7 & f&Q 39_fVJHR &, 3x Ta #1 & f4 vMT (iii) qf 3HdR GRT #1} 9v7 &67 7a f841 JaT &, 3f7 3rzar ERT 3T 7d f241 JaT & a 3 5A # fr 31} & Td f4t viQT Ja 7r B7461 %8 qietut _ YFaGT TcA &1 7 &87 &Q 7a 767 @la Note English version of the instructions is printed on the back cover of this Booklet. CEBN-S-GKL (1-A) %uifa qieut 504 Tryri yfrht 34a fa - f - Tfa fr - fau ~",
    "1 Consider the following statements with Which of the following statements with reference to Secondary waves (S-Waves) reference to Surface inversion of temperature generated during an earthquake islare correct ? 13 They  create troughs and crests in the 1 It causes instability in the layers of material through which they pass. the atmosphere. 2_ The direction of vibrations of S-waves is 2. This inversion commonly lasts for a few perpendicular to the wave direction in hours the Sun comes up. the vertical plane Select the answer the code given below Which of the  statements   given above   islare (a) 1 only correct ? (b) 2 only (a) 1 only (c) Both 1 and 2 (b) 2 only (d) Neither 1 nor 2 (c Both 1 and 2 (d) Neither 1 nor 2 5. Identify the cloud on the basis of the following characteristics relating to it 2. Identify the Mineral on the basis of the I They look like cotton wool_ following characteristics relating to it : II. They exist in patches and have flat base_ I It is usually a greenish crystal: III. They are generally formed at a height of II. It is often found in basaltic rocks_ 4 to 7 km_ III Magnesium, iron and silica are its major Select the answer using the code below elements_ (a) Cirrus Select the answer the code given below (b) Cumulus a) Amphibolite (c) Nimbus (b) Feldspar (d) Stratus (c Pyroxene (d) Olivine 6 Identify the type of climate on the basis of the following characteristics relating to it 3- Which of the following statements with I Temperature is high throughout the reference to Salt Weathering islare correct ? year 1 Salt crystallisation is the most effective II: Rainfall is variable   with a short wet of all the salt weathering processes_ season and a longer dry season. 2 Salt crystal growth is more effective over III Climate of Sudan and Paraguay is an sedimentary rocks as compared to example of this climate type_ igneous rocks. Select the answer using the code given below Select the answer using the code given below (a) Sub-tropical steppe climate (a) 1 only (b) Mid-latitude steppe (b) 2 only (c) Both 1 and 2 (c) Tropical monsoon climate (d) Neither 1 nor 2 (d) Tropical and dry climate CEBN-S-GKL (3 - A ) lower until using given using wet",
    "7 What is the correct sequence of the following 11. Which of the following statements with salts in  ascending order   according to their reference to Easter Island, UNESCO World presence in the sea water ? Heritage Site, islare correct ? 1_ Calcium Carbonate 1 It is of Polynesia group of islands. 2 Calcium Sulphate 2 It is territory of the South American 3. Magnesium Chloride nation Chile. Select the answer the code given below Select the answer the code given below (a) 3,1,2 (a) 1 only (b) 1,3, 2 (b) 2 only (c) 1,2, 3 (c) Both 1 and 2 (d) 2,1, 3 (d) Neither 1 nor 2 8. Which of the following statements with reference to Humus islare correct ? 1 It is a dark coloured amorphous 12. Which one among the following is home to the substance endangered mountain gorillas in Africa ? 2 colloidal in nature, it serves as a reservoir of nutrients. (a) Mount Kenya Select the answer the code given below (b) Mount Kilimanjaro (a) 1 only (c) Ngorongoro Crater (b) 2 only (c) Both 1 and 2 (d) Virunga Mountains (d) Neither 1 nor 2 9. Which one among the   following Biosphere 13. Which of the following statements with Reserves is spread over three states in India ? reference to Jordan islare correct ? (a) Dehang Debang 1. The country of Jordan was created (b) Nilgiris through the British Mandate after World (c) Nokrek War I. (d) Seshachalam 2 It is a landlocked country 10. River Danube does not through which one Select the answer using the code given below of the following capital cities in Europe ? (a) 1 only (a) Belgrade (b) 2 only Budapest (c) Prague (c) Both 1 and 2 (d) Vienna (d) Neither 1 nor 2 CEBN-S-GKL (5-A ) part using - using Being using flow",
    "14. Which one among the   following places is 17. Which of the following statements with situated close to the Pearl River Estuary in reference to saline in India islare correct ? Asia ? 13 They are rich in nitrogen. (a) Bangkok 2. They occur in arid and semi-arid regions, Hong Kong and in waterlogged and swampy areas. Macau Select the answer the code given below (d) Singapore (a) 1 only (b) 2 only (c) Both 1 and 2 15. Consider the following statements with regard (d) Neither 1 nor 2 to Australia 1 The Coral Sea separates the Great 18. Salal Power Project is situated on which one Barrier Reef from the South Pacific. among the following rivers ? 2 The Great Dividing Range extends from (a) Chenab Melbourne to Perth in Australia: (b) Jhelum Which of the  statements  given above islare (c) Nubra correct ? (a) 1 only (d) Shyok (b) 2 only (c) Both 1 and 2 19. Which one among the following tributaries of Indus River does not originate in the d) Neither 1 nor 2 Himalayas ? (a) Gilgit 16. What is the correct sequence of the following (b) Gomal mountain ranges as one moves   from North (c) Hunza towards South ? (d) Zaskar 1 Karakoram 2 Kunlun 20. As per the Annual Report 2023 24 of the 3 Ladakh Ministry of Mines, Government of India, which 4_ Zaskar of the following are the major bauxite Select the answer using the code given below producing states in India ? (a) 1,2,3,4 (a) Odisha and Madhya Pradesh (b) 1,2,4, 3 Odisha and Jharkhand (c) 2,1,4,3 Jharkhand and Madhya Pradesh (d) 2,1,3,4 (d) Jharkhand and Karnataka CEBN-S-GKL (7A ) soil using",
    "21. If your image appears to be erect, no matter 24. The minimum power required to lift a mass of how far you stand from a mirror; the mirror is 50 kg up to a vertical distance of 8 m in 10 $ likely to be is (Take g = 10 m/s2) (a) Plane (a) 400 W Concave (b) 40 W Convex (c) 50 W (d) Either plane or convex (d) 500 W 22. The rule that determines the  direction of 25. Which one among the following statements is magnetic field   produced around a straight not correct ? conductor carrying current is (a) All bodies in the universe attract each (a) Right-hand thumb rule other due to the gravitational force_ Fleming's left-hand rule Newton's law of gravitation follows from Newton's of motion Fleming s right-hand rule (c The value of g (acceleration due to (d) Hund s rule gravity) at the centre of the Earth is zero. (d) Mass and weight are measured in different units 23. A motorcycle has initial velocity of 5 m/s. After 3 seconds, the velocity is 7 mls. The displacement of the motorcycle in 3 seconds is 26. A body floats in a liquid if the buoyant force is (a) 21 m (a) to its weight: (b) 18 m (b) less than its weight. (c) 36 m (c) greater than its weight. (d) 6 m (d) zero CEBN-S-GKL ((9 _ A ) laws equal",
    "27. metallic sphere of mass 1 kg and volume 31. Which of the following is one of the 'three gems' 2 x 10 is completely immersed in water_ (triratna) of Jainism ? The buoyant force exerted by water on (a) Brahmacharya the sphere is (b) Samyag-darshana (Given density of water = 1000 kglm? , (c) Sunrita g = 10 m/s2) (d) Asteya (a) 05 N (b) 1+5 N (c) 2 N 32. Which one among the following motifs does not (d) 25 N appear on Harappan seals ? (a) Humped Bull Elephant 28. light bulb rated as 60 W at 220 V has a (c Lion potential difference of 110 V across its ends. (d) Crocodile The power dissipated in this light bulb is (a) 30 W 45 W 33. Which one among the following is the earliest 15 W text ? (d) 2 W (a) Natyashastra of Bharata (b) Sushruta Samhita 29. Which one among the following is used in (c) Ashtadhyayi simple microscope ? (d) Manusmriti (a) Diverging lens (b) Concave mirror 34. Which one of the following statements about (c) Converging lens Ashoka's inscriptions is correct ? (d) Plane mirror (a) The Major Rock Edict found in Kerala is in Sanskrit: 30. The force with which the Earth attracts an (b) Minor Rock Edicts in Bihar are found object is called only in Pataliputra: (a) Weight of the object The Dhauli Major Rock Edict makes Mass of the object mention of the Kalinga War. (c) Density of the object (d) Kalsi in Uttarakhand is site of Major (d) Magnitude of the object Rock Edicts. CEBN-S-GKL (11 _ A ) m8",
    "35. Which one of the following statements about 38. Which one of the following does not refer to the the Ajivikas is not correct ? bow (and arrow) as a weapon of war in ancient (a) They did not practise discrimination on India ? the basis of caste or class. (a) Sharnga b) They had corporate organisation and canonical texts_ (b) Kunta practised severe asceticism, often Kodanda eating very little food. They formed an alliance with Jainas (d) Karmuka against Buddhists. 39. What is the military-device referred to by the 36. Consider the following statements about the term manjaniq ? use of stirrup in India 1 The Konarak horse   sculpture (c 1250) (a) A device for   loading   field-guns with shows a ring-stirrup  gunpowder 2 A broad, probably wooden , stirrup b) Preparing cavalry for rapid charge appears in Khajuraho sculptures (probably 1th century) (c) A bolting device for strengthening the of forts 3 The iron-stirrup was used in the Delhi Sultans' armies from the thirteenth (d) A device for throwing stones (mangonel) century onwards. How many of the above statements is/are correct ? 40. In medieval India, the process of indigo (a) 1 extraction underwent great improvement as a (b) 2 result of the (c) 3 (a) use of fertilizer enhancing the quality of (d) Nil indigo crop. (b) introduction of mechanical crushing tools 37. In the Veda  Samhita, use of the terms for indigo stems. ishukrit and isukara referred to the maker of : use of gypsum and lime mortars in (a) Arrows making the inner surfaces of indigo vats Swords water- Vajra (Thunderbolt) (d) employment of slave labour in (d) Maces desilting of indigo crucibles. CEBN-S-GKL (13 _ A ) They gates Rig proof. quick",
    "41. Which one of the following is listed in the Ain-i 44. Which one of the following statements about Akbari as one of the Indian sciences' prescribed Rig Vedic goddesses is correct ? by Akbar for scholars to learn at school ? (a) Ushas represents freedom from sickness. (a) Ayurveda (b) Sinivali bestows children. Vyakarana (c) Aditi is goddess of Ganita (d) Raka is goddess of speech. (d) Jyotisha 45. Which one of the following statements about 42. Consider the following statements about the the Buddhist Goddess Hariti is correct ? arms used by Europeans in warfare in India (a) She was converted by the Buddha from a 1 The flint-lock muskets could work even in blood-thirsty   yakshi to benevolent wet weather  maternal figure. 2 The addition of bayonet made musket a She is the feminine  personification of more effective and dangerous weapon in wisdom_ close combat. She protects from eight  great 3 The wrought-iron cannon barrels were fears_ easy to move and manoeuvre_ She is a warrior goddess associated with How many of the above statements islare the dawn_ correct ? (a) (b) 2 46. Consider the following statements about the (c) 3 literary language Apabhramsha (d) Nil 1. It appeared in recognizable forms by the sixth century  43 Which one of the following statements about 2 It developed out of mixtures of regional the grammarian Katyayana is correct ? vernaculars with the Prakrits and Sanskrit. (a) He was a contemporary of Panini. Which of the statements given above islare He was a contemporary of Patanjali: correct ? He belonged to a period between Panini (a) 1 only and Patanjali. (b) 2 only (d) He belonged to a period later than both (c Both 1 and 2 Panini and Patanjali: (d) Neither 1 nor 2 CEBN-S-GKL (15 _ A ) dawn- people",
    "47. Who   composed Zainavilas, history of the 51_ Isobars of elements have same rulers of   Kashmir, in the time of Zainul (a) Atomic numbers. Abidin ? (b) Number of electrons. (a) Bhattavatara (c) Mass numbers. (b) Jonaraja (d) Number of neutrons. (c) Shrivara 52. Which one of the   following could not be (d) Vachaspati explained by Rutherford's nuclear model ? (a) Stability of the atom 48. In which one of the following works has Amir (b) Presence of nucleus in the centre of an Khusrau praised the climate of   India, its atom languages, notably Sanskrit, its arts and music (c) Comparison of sizes of atom and nucleus and even its animals ? (d) Nucleus is positively charged (a) Ijaz-i Khusrawi (b) Dewal Rani Khizr Khani 53. If  atomic number of an element is 11, the (c) Khazainul Futuh correct name, symbol and valency are (d) Nuh Sipihr (a) Lithium, Li, 1 (b) Magnesium, Mg, 2 49. Which one of the following works was written (c) Boron, B, 3 in early eighteenth century by the Bengali (d) Sodium, Na, 1 Rameshwar Bhattacharya ? 54. Which one of the  following gas is used in (a) Dharmamangal making soft drinks ? (b) Shivsankirttan (a) NH3 (c) Mansimha (b) PH3 (d) Vidyasundar (c) COC1z (d) 50. Which one of the following present territories was outside the limits of Ashoka s 55. Which one of the following is considered as a empire ? compound ? (a) Brahmaputra valley, Assam (a) Silicon Baluchistan (b) Tin (c) North Bengal (c) Sugar solution (d) Kashmir valley (d) Calcium carbonate CEBN-S-GKL (17 _ A ) poet CO2 day",
    "56. Rutherford s &-particle scattering experiment 61. Consider the following statements with respect on gold foil is responsible for the discovery of : to performance of the merchandise export of (a) Neutron India in FY 2024 Electron 1_ Share of capital such as machinery, Proton equipment and other durable decreased substantially. d) Atomic nucleus 2 Share of consumer goods and intermediate goods increased_ 57. Which one of the following is a metalloid ? Which of the statements given above islare (a) Germanium correct ? (b) Coke (a) 1 only (c) Iodine (b) 2 only (d) (c) Both 1 and 2 (d) Neither 1 nor 2 58. Which one of the following is not explained by the Dalton's atomic theory ? (a) of conservation of mass 62. Which one among the   following statements (b) Law of constant composition about Project Nexus is correct ? (c) Presence of different kind of sub-atomic (a) It is an international agreement to particles in an atom enable labour movement between (d) of multiple proportion countries_ 59. Which one of the following contains all Lewis (b) It is an international initiative to enable acids ? instant cross-border retail payments. (a) AlClz, Co8+ BF (c) It is an international initiative to transfer technology between countries_ (b) BClg; NHg; OH- (d) It is an international agreement to create (c) 2+ H2O,F- database on financial inclusion. (d) BF3, NH3; HzO 63. While   calculating the consumer index; 60. Number   of electrons   present in the   species housing' as an item is classified as Hz, He, Hz and 02 respectively are (a) Core consumer durable (a) 1,2,2, 15 (b) consumer non-durable (b) 1,2,1,14 2,2,2, 16 Core capital (d) 0,2,1,14 (d) Core service CEBN-S-GKL 19 _ A ) goods goods Sugar Law Law Mg price Core goods",
    "64. Which one among the following established the 67 . Core inflation is (a) CPI headline inflation minus all non-food first Global Capability Centre in India ? items (a) Honeywell (b) WPI inflation minus all food and (b) Citibank non-food items (c Texas Instruments (c) CPI headline inflation minus food and (d) SAP Labs India energy items (d) WPI inflation minus food and energy items 65. Which ofthe following pairs islare not correctly 68. In alignment with the guidelines of NEP 2020, matched ? Poshan bhi Padhai bhi' (PBPB) was launched under which one among the following 1 Global Value International programmes ? Chains (GVC) Product Sharing (a) Integrated Teacher Training Programme 2 World Integrated Database on GVC (b) Vidya Pravesh Trade Solutions related Trade (c) Early Childhood Care and Education 3 Current Account Foreign Direct (d) Samagra Shiksha Abhiyan Deficit (CAD) Investment 69. Which one among the following defines flexi Select the answer using the code given below workers in India ? (a) 1 and 2 only (a) Formal contract staff employed through (b) 2 and 3 only organised contract (c) 3 only (b) Informal sector employees   working in urban areas (d) 1,2 and 3 (c) Agricultural labour migrating to urban areas 66. How can currency depreciation  stimulate an (d) Regular salaried workers working in increase in net exports ? registered companies 1_ By reducing export costs 70. Which one among the following is an integrated 2 By reducing import prices teacher training programme 2 Select the answer using the code given below (a) Vidya Pravesh (a) 1 only b) NISHTHA (b) 2 only Vidyanjali Both 1 and 2 (d) DIKSHA (d) Neither 1 nor 2 CEBN-S-GKL (21 _ A )",
    "71. Which instrument is used to measure the blood 76. Sponges   belong to which one among the pressure manually ? following phylum ? (a) Sphygmomanometer (a) Porifera (b) Centrifuge (b) Platyhelminthes Electrophoresis (c) Cnidaria (d) Thermal cycler (d) Annelida 72. Myopia is also known as 77. Lactose is made up of : (a) Far-sightedness (a) Glucose only (b) Near-sightedness (b) Glucose and Fructose Cataract (c Glucose and Sucrose (d) Presbyopia (d) Glucose and Galactose 73. Why does the Rough Endoplasmic Reticulum 78. The enzymes which catalyze the same reaction look 'rough' under a microscope ? but different amino acid compositions are (a) Due to the presence of ribosomes on its surface commonly referred as Due to the absence of ribosomes on its (a) Isoenzymes surface (b) Isotopes Due to the presence of lysosomes on its surface (c) Isomers (d) Due to the presence of mitochondria on (d) Coenzymes surface 79. How many Carbon atoms are present in 74. Which one among the following is not a plant hormone ? Pyruvate molecule ? (a) Gibberellins (a) 2 (b) Abscisic acid (b) 3 Auxins (c) 4 (d) Thyroxine (d) 5 75. The normal systolic pressure in human 80. The human eye has point that lacks is photoreceptor cells. This is identified as (a) 80 mm of (a) Fovea (b) 100 mm of Hg (b) Blind (c) 120 mm of (c) Dark (d) 140 mm of (d) Orbit CEBN-S-GKL ((23 _ A ) 0 ' ` have its beings Hg spot Hg spot Hg",
    "81. Which of the following Constitution 84. International of Democracy, as   decided Amendment Acts introduced GST (Goods and vide a UN General Assembly  resolution, is Services Tax) in course of inter-state trade or commerce ? observed on (a) Constitution (One Hundred and First (a) 20 January Amendment) Act (b) 1 July (b) Constitution (One Hundred and Second (c 15 September Amendment) Act (d) 9 December (c) Constitution (One Hundred and Fourth Amendment) Act (d) Constitution (One Hundred and Sixth 85. Which of the following statements about the Amendment) Act NITI Aayog islare correct ? 1_ Prime Minister of India is the 82. Which one among the following UN agencies Chairperson of  Governing Council. has received the Nobel Prize more than once ? 2 Lieutenant Governor of Ladakh is (a) ILO member of its Governing Council: (b) WFP Select the answer using the code given below (c) UNICEF (a) 1 only d) UNHCR (b) 2 only Both 1 and 2 83_ Consider the following statements about (d) Neither 1 nor 2 Central Vigilance Commission (CVC) 1. Central Vigilance Commissioner is 86. Which of the following statements about appointed by the President of India. National Commission for Women are correct ? 2 The Committee to recommend the appointment of Central Vigilance 1 It is a statutory body. Commissioner the Minister of Home Affairs a8 one of the members. 2 It has the mandate to review the constitutional and legal  safeguards  for 3 In certain circumstances the Leader of women_ the single largest group in opposition in Lok Sabha can be on the Committee to 3 It has the mandate to advise the recommend the appointment of Central Government on all policy matters Vigilance Commissioner. affecting women How many of the above statements islare Select the answer using the code given below correct ? (a) Nil (a) 1 and 2 only (b) 1 (b) 2 and 3 only (c) 2 (c) 1 and 3 only (d) 3 (d) 1,2 and 3 CEBN-S-GKL (25 _ A ) Day its has",
    "87. Which, amongst the  following, is the latest 90. Which of the following statements islare correct language to be included in the Eighth Schedule as per the Constitution of India ? of the Constitution of India ? 1 The Constitution (Eighty-sixth (a) Maithili Amendment) Act has added the Right to (b) Nepali Education to the   chapter of   Directive Principles of State Policy. (c) Konkani (d) Manipuri 2 Right to Work and Right to Education are both, Fundamental Rights and Directive Principles of State Policy. 88. Which one among the following states has the Select the answer the code given below highest  number of' seats in the Council of States ? (a) 1 (b) 2 only (a) Andhra Pradesh (c) Both 1 and 2 Bihar (d) Neither 1 nor 2 (c) Madhya Pradesh d) Tamil Nadu 91. As defined in Article 12 of the Constitution of 89. Which of the following statements about the India; 'State' includes Indus Waters Treaty islare correct ? 1 Parliament of India 13 The term Eastern Rivers' means the Sutlej; the Beas and the Ravi taken 2. State Governments together: 2 The term Western Rivers' means the 3_ State Legislatures Indus, the Jhelum and the Chenab taken together: Local authorities in India Select the answer the code below Select the answer using the code given below (a) 1 only (a) 1 and 3 only (b) 2 only (b) 1,2 and 3 only (c) Both 1 and 2 (c) 1,2,3 and 4 (d) Neither 1 nor 2 (d) 2 and 4 only CEBN-S-GKL (27 _ A ) using only given using",
    "92. Which of the following descriptions with regard 95. Who among the following was responsible for to Parliamentary Privilege for Members of the demarcating the borders between India and Parliament of India islare correct ? Pakistan during the partition in 1947 ? 1 The Speaker is empowered to refer suo moto any question of privilege for (a) Cyril Radcliffe investigation (b) Mortimer Durand 2  A question of privilege is accorded priority over other items in the List of Henry McMahon Business 3 The privilege  extends to freedom from (d) Arthur Belfour preventive arrest or detention Select the answer the code given below (a) 1 only 96. Which one among the following   statements (b 2 and 3 only about Dr. Muthulakshmi  Reddy, freedom (c) 1 and 2 only fighter, is not correct ? (d) 1,2 and 3 (a) She was the   first   girl student to be admitted into a men s college. 93. Which one among the   following statements (b) She was the first woman legislator in about an adjournment motion in the British India. Parliament of India is not correct ? (a) Its objective is to draw attention of the She was a medical professional House to any recent matter of urgent (d) She was honoured with Bharat Ratna in public importance. 1956. (b) Adjournment motion is an extraordinary procedure. (c) This motion can be invoked on any 97. \"Since wars begin in the minds of men, it is in matter of urgent importance that may the minds of men that the defences of peace even be within the jurisdiction of a State must be constructed: This observation can be Government. found in the Constitution of which one of the (d) The Chair has absolute discretion to refuse consent. following Organs of the United Nations ? a World Health Organisation 94. The Kyoto Protocol specifically relates to which one among the following issues ? United Nations   Educational, Scientific and Cultural Organisation (a) Emission reduction (b Ozone layer depletion International Atomic Energy Agency Chlorofluorocarbons (d) United Nations Economic and Social Council (d) Biodiversity management CEBN-S-GKL ((29 _ A ) using -",
    "98. Which one among the   following countries 101. Which one among the following is the purpose of firewall ? does not share its territorial boundary with (a) Preventing unauthorised access to Ukraine ? computer via the internet (a) Poland (b) Installation of software that can harm Romania the computer (c) Lithuania C) Recording   everything that is done on (d) Belarus computer (d) Running checks to prevent virus attacks 99. Which of the   following statements islare 102. Which one of the following is not an application correct ? software ? 1_ First Law Commission recommended (a) Spreadsheet Indian Penal Code, 1860. (b) AutoCAD 2_ Indian Penal Code, 1860 has been completely replaced by the Bharatiya MS PowerPoint Nyaya Sanhita, 2023. (d) Linker Select the answer the code given below (a) 1 only 103. Which among the following   is a malicious software ? (b) 2 only (a) Hacking (c) Both 1 and 2 (b) Password Cracking (d) Neither 1 nor 2 (c) Trojan Horse (d) Firewall 100. Consider the following statements with regard to the   setting up of the Backward Class 104. What is an interactive combination of text, Commission in India graphics, video, audio and images termed as ? 13 The First Backward Class Commission, (a) JPEG set up by the Government of India, is (b) Multimedia popularly known as Kaka Kalelkar Commission_ (c) AVA 2 The Third Backward Class Commission, (d) PNG set up by the Government of India, is popularly known as Mandal Commission. 105. Which one of the following is the characteristic Which of the statements given above islare of Artificial Intelligence ? correct ? (a) Replicates human decision making (a) 1 only (b) Stores relevant information (b) 2 only (c) Stores similar kind of data for specific (c) Both 1 and 2 purpose Neither 1 nor 2 (d) Allows user to interact with media CEBN-S-GKL (31 - A ) using",
    "106. Which organisationlinstitute has recently 109. The Paramparagat Krishi Vikas Yojana (PKVY) launched in 2015 16 by the Central started the new initiatives   such as Bharat Government is aimed to Vidya Pariyojana, Brihattar Bharat and Nari (a) make agriculture more modern and Samvaad Prakalp ? globally competitive_ (a IGNOU (b) provide improved access to irrigation and (b) Sahitya Akademi enhanced water efficiency. (c Centre for Cultural Resources and (c) support promotion of organic farming in the country. Training (CCRT) (d) reduce dependence of agriculture on (d) Indira Gandhi National Centre for Arts monsoon (IGNCA) 110. When did the Union Government establish a 107. Which one among the   following educational separate   Ministry  of Cooperation' with the vision of \"Sahkar Se Samriddhi\" ? institutions established under the Union (a) 2014 Ministry of Culture is promoting to preserve, (b) 2016 protect and promote Lord Buddha's teaching (c) 2018 and value of love, compassion and non-violence (d) 2021 for developing moral values and practices ? 111. The Ministry of Defence, Government of India, (a) Indian Institute of Advanced Study, has declared 2025 as the year of Shimla (a) Rehabilitation of the families of martyrs National Council of Educational (b) Reforms Research & Training, New Delhi (c) Peace (d) Self-reliance Nava Nalanda Mahavihara, Nalanda (d) IGNOU, New Delhi 112. Which of the following statements about Network for Digital Commerce (ONDC) islare correct ? 108.  \"Nirbhaya Fund\" , a non-lapsable corpus fund, 1 It was launched in 2021 by the which is to be utilized for the projects Government of India. specifically designed to improve the safety and 2 Its aim is to democratize e-commerce in security of women is administered by India. 3. India surpassed China in 2024 in (a) The Ministry of Women & Child e-retail penetration. Development Select the answer using the code given below (b) The Ministry of Home Affairs (a) 1,2 and 3 (b) 1 and 2 only (c) The Ministry of Finance (c) 2 and 3 only d) The Ministry of Education (d) 3 only CEBN-S-GKL (33 _ A ) good Open has",
    "113. \"Million Minds Augmenting National 116. The Order of Mubarak Al-Kabeer' is the Aspirations and Knowledge\" (MANAK), a highest national award of scheme under the flagship programme, (a) Egypt Innovation in Science Pursuit for Inspired (b Kuwait Research (INSPIRE), caters to (c Bahrain (d) United Arab Emirates (a) The college students   studying in the undergraduate programme in the age group of 19 25 years _ 117. Bald eagle has recently been officially declared as the national bird of which one among the (b) The research scholars in recognized following countries ? research laboratories of national (a) China importance. (b) England (c) The college teachers of the country_ (c) USA (d) The school children studying in classes (d) Ireland 6 _ 10 in the age group of 10 15 years _ 118.  Surya Kiran is ajoint military exercise between India and 114. Who among the following were awarded the Major Dhyan Chand Khel Ratna Award 2024 ? (a) Bangladesh (b) Bhutan 1_ Shri Gukesh D (c) Singapore 2  Shri Harmanpreet Singh (d) Nepal 3 Shri Praveen Kumar 119. Which of the following statements islare correct ? 4 Ms. Manu Bhaker 1 Moidam-The Mound-Burial system of the Select the answer using the code given below Ahom dynasty was inscribed in the (a) 1,2, 3 and 4 UNESCO World Heritage list. 2 The Government of India conferred the (b) 1 and 4 only status of classical language to Pali; Assamese, Bengali and Maithili. (c) 1,2 and 4 only 3 Project PARI is an initiative of Ministry (d) 2 and 3 only of Education. Select the answer using the code given below 115. Consider the   following statements about a (a) 2 only prominent film personality of India (b) 1 only He was born in Hyderabad: He emerged in the (c) 2 and 3 only 1970s   with series of films that challenged (d) 1,2 and 3 mainstream Bollywood: He became widely known for Bharat Ek Khoj, a landmark 120. Which one of the following PSLVs, launched by 53-episode television series. He directed a 2023 ISRO, is not correctly matched with their Missions ? biopic about Sheikh Mujibur Rahman. PSLV Mission Identify the personality from the following (a) PSLV C60 SPADEX (a) Govind Nihalani (b) PSLV C59 Proba-3 (b) Girish Karnad (c) PSLV C58 XPoSat (c) Shyam Benegal (d) PSLV C57 DS-SAR (d) Mani Ratnam CEBN-S-GKL 35 _ A )",
    "43&T & Te SPACE FOR ROUGH WORK CEBN-S-GKL ((37 _ A ) {> fr \"",
    "T7 &T & e SPACE FOR ROUGH WORK \".. . CEBN-S-GKL 39 _ A ) f& -"
  ]